/* eslint-disable prettier/prettier */
export const SET_USER = 'SET_USER';
export const SET_DISCOUNT = 'SET_DISCOUNT';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const SET_CUSTOMER_INVOICE = 'SET_CUSTOMER_INVOICE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_NOTES = 'SET_NOTES';
export const ADD_TO_PRODUCT = 'ADD_TO_PRODUCT';
export const ADD_TO_PRODUCT_CHAIN = 'ADD_TO_PRODUCT_CHAIN';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_CHAIN = 'REMOVE_FROM_CART_CHAIN';
export const REMOVE_PRODUCT_FORM_CART = 'REMOVE_PRODUCT_FORM_CART';
export const REMOVE_PRODUCT_FORM_CART_CHAIN = 'REMOVE_PRODUCT_FORM_CART_CHAIN';
export const SET_DELIVERY_ADDRESS = 'SET_DELIVERY_ADDRESS';
export const SET_CURRENCY = 'SET_CURRENCY';
export const FORMAT_CURRENCY = 'FORMAT_CURRENCY';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const CLEAR_ORDER_CHAIN = 'CLEAR_ORDER_CHAIN';
export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART_CHAIN = 'CLEAR_CART_CHAIN';
export const UpdateTabbar = 'UpdateTabbar';
export const SET_SUPPLIER = 'SET_SUPPLIER';
export const RESET = 'RESET';
export const RESET_DELIVERY = 'RESET_DELIVERY';
export const RESET_DELIVERY_MAIN = 'RESET_DELIVERY_MAIN';

export const UPDATE_CART = 'UPDATE_CART';
export const ORDER_RELOAD = 'ORDER_RELOAD';
export const PRODUCT_RELOAD = 'PRODUCT_RELOAD';
export const PRODUCT_CATEGORY_RELOAD = 'PRODUCT_CATEGORY_RELOAD';
export const CUSTOMER_RELOAD = 'CUSTOMER_RELOAD';
export const PRODUCT_FILTERS = 'PRODUCT_FILTERS';
export const ADD_DELIVERY_FEE_TO_COST = 'ADD_DELIVERY_FEE_TO_COST';
export const REMOVE_DELIVERY_FEE_TO_COST = 'REMOVE_DELIVERY_FEE_TO_COST';

export const CAPTURE_BARCODE = 'CAPTURE_BARCODE';
export const PRODUCT_CATEGORY_FILTER_RELOAD = 'PRODUCT_CATEGORY_FILTER_RELOAD';



export const IS_FETCHING_PRODUCTS = 'IS_FETCHING_PRODUCTS';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const IS_FETCHING_PRODUCTS_ERROR = 'IS_FETCHING_PRODUCTS_ERROR';
export const PRODUCT_FETCHED_MORE = 'PRODUCT_FETCHED_MORE';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_CREATED_ERROR = 'PRODUCT_CREATED_ERROR';
export const IS_PRODUCT_SUBMITTING = 'IS_PRODUCT_SUBMITTING';
export const UPDATE_PRODUCT_FROM_CART = 'UPDATE_PRODUCT_FROM_CART';


export const IS_CREATING_CUSTOMER = 'IS_CREATING_CUSTOMER';
export const IS_FETCHING_CUSTOMER = 'IS_FETCHING_CUSTOMER';
export const CUSTOMER_CREATED = 'CUSTOMER_CREATED';
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED';
export const CUSTOMER_FETCHED_MORE = 'CUSTOMER_FETCHED_MORE';
export const CUSTOMER_FETCHED = 'CUSTOMER_FETCHED';
export const FETCHING_CUSTOMER_ERROR = 'FETCHING_CUSTOMER_ERROR';



export const IS_FETCHING_PRODUCTS_CATEGORY = 'IS_FETCHING_PRODUCTS_CATEGORY';
export const PRODUCT_CATEGORY_FETCHED = 'PRODUCT_CATEGORY_FETCHED';
export const IS_FETCHING_PRODUCTS_CATEGORY_ERROR = 'IS_FETCHING_PRODUCTS_CATEGORY_ERROR';
export const PRODUCT_CATEGORY_FETCHED_MORE = 'PRODUCT_CATEGORY_FETCHED_MORE';
export const PRODUCT_CATEGORY_CREATED = 'PRODUCT_CATEGORY_CREATED';
export const PRODUCT_CATEGORY_UPDATED = 'PRODUCT_CATEGORY_UPDATED';
export const PRODUCT_CATEGORY_CREATED_ERROR = 'PRODUCT_CATEGORY_CREATED_ERROR';
export const IS_PRODUCT_CATEGORY_SUBMITTING = 'IS_PRODUCT_CATEGORY_SUBMITTING';





